<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ApiDocsController extends Controller
{
    public function index()
    {
        $apis = [
            'Public / Miscellaneous' => [
                ['method' => 'GET', 'endpoint' => '/api/', 'description' => 'Check if backend is running.', 'requires_auth' => false, 'parameters' => [], 'response' => '{"message": "Backend is running"}'],
                ['method' => 'GET', 'endpoint' => '/api/redirectwhatsapp', 'description' => 'Redirect to WhatsApp Contact Us.', 'requires_auth' => false, 'parameters' => [], 'response' => 'Redirects to WhatsApp URL'],
                ['method' => 'GET', 'endpoint' => '/api/clear-cache', 'description' => 'Clear application caches (dev).', 'requires_auth' => false, 'parameters' => [], 'response' => '{"status": true, "message": "All caches cleared successfully"}'],
                ['method' => 'GET', 'endpoint' => '/api/migrate', 'description' => 'Run database migrations.', 'requires_auth' => false, 'parameters' => [], 'response' => '{"status": true, "message": "Migrations executed successfully"}'],
                ['method' => 'GET', 'endpoint' => '/api/passport-install', 'description' => 'Install Laravel Passport.', 'requires_auth' => false, 'parameters' => [], 'response' => '{"status": true, "message": "Passport installed successfully"}'],
                ['method' => 'GET/POST', 'endpoint' => '/api/whatsapp/webhook', 'description' => 'WhatsApp verification and incoming messages webhook.', 'requires_auth' => false, 'parameters' => [], 'response' => 'Returns WhatsApp Hub Challenge or 200 OK'],
                ['method' => 'GET', 'endpoint' => '/api/conversations/media/signed/{conversationId}/{mediaId}', 'description' => 'Signed conversation media (no auth required).', 'requires_auth' => false, 'parameters' => [], 'response' => 'Returns media file'],
                ['method' => 'GET', 'endpoint' => '/api/media/{filename}', 'description' => 'Public media routes.', 'requires_auth' => false, 'parameters' => [], 'response' => 'Returns media file'],
            ],
            'Authentication & Profile' => [
                ['method' => 'POST', 'endpoint' => '/api/auth/register', 'description' => 'Register a new user account.', 'requires_auth' => false, 'parameters' => [['name' => 'name', 'type' => 'string', 'required' => true, 'description' => 'Full name', 'example' => 'John Doe'],['name' => 'email', 'type' => 'string', 'required' => true, 'description' => 'Email', 'example' => 'john@example.com'],['name' => 'number', 'type' => 'string', 'required' => true, 'description' => 'Phone', 'example' => '+1234567890'],['name' => 'password', 'type' => 'string', 'required' => true, 'description' => 'Password (min 8)', 'example' => 'secret123'],['name' => 'role', 'type' => 'string', 'required' => false, 'description' => 'admin/user', 'example' => 'user']], 'response' => '{"status": true, "message": "Registration successful", "token": "..."}'],
                ['method' => 'POST', 'endpoint' => '/api/auth/login', 'description' => 'Authenticate a user.', 'requires_auth' => false, 'parameters' => [['name' => 'email', 'type' => 'string', 'required' => true, 'description' => 'Email', 'example' => 'john@example.com'],['name' => 'password', 'type' => 'string', 'required' => true, 'description' => 'Password', 'example' => 'secret123']], 'response' => '{"status": true, "token": "..."}'],
                ['method' => 'GET', 'endpoint' => '/api/auth/profile', 'description' => 'Get user profile.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "user": {...}}'],
                ['method' => 'POST', 'endpoint' => '/api/auth/edit-profile', 'description' => 'Edit profile (works with PUT or POST for files).', 'requires_auth' => true, 'parameters' => [['name' => 'name', 'type' => 'string', 'required' => true, 'description' => 'Name', 'example' => 'John Doe'],['name' => 'email', 'type' => 'string', 'required' => true, 'description' => 'Email', 'example' => 'john@example.com'],['name' => 'number', 'type' => 'string', 'required' => false, 'description' => 'Phone', 'example' => '+1234567890'],['name' => 'bio', 'type' => 'string', 'required' => false, 'description' => 'Bio', 'example' => 'Software Developer'],['name' => 'companyName', 'type' => 'string', 'required' => false, 'description' => 'Company Name', 'example' => 'Acme Corp'],['name' => 'companyAddress', 'type' => 'string', 'required' => false, 'description' => 'Company Address', 'example' => '123 Main St'],['name' => 'companyEmail', 'type' => 'string', 'required' => false, 'description' => 'Company Email', 'example' => 'contact@acme.com'],['name' => 'companyMobile', 'type' => 'string', 'required' => false, 'description' => 'Company Mobile', 'example' => '+19876543210'],['name' => 'profileImage', 'type' => 'file', 'required' => false, 'description' => 'Avatar', 'example' => 'avatar.jpg'],['name' => 'companyLogo', 'type' => 'file', 'required' => false, 'description' => 'Logo', 'example' => 'logo.png']], 'response' => '{"status": true, "message": "Profile updated successfully"}'],
                ['method' => 'POST', 'endpoint' => '/api/auth/test-upload', 'description' => 'Test file upload.', 'requires_auth' => true, 'parameters' => [['name' => 'testFile', 'type' => 'file', 'required' => false, 'description' => 'File for testing', 'example' => 'test.pdf']], 'response' => '{"status": true, "debug": {...}}'],
                ['method' => 'PUT', 'endpoint' => '/api/auth/change-password', 'description' => 'Change password.', 'requires_auth' => true, 'parameters' => [['name' => 'currentPassword', 'type' => 'string', 'required' => true, 'description' => 'Current password', 'example' => 'secret123'],['name' => 'newPassword', 'type' => 'string', 'required' => true, 'description' => 'New password', 'example' => 'newsecret123'],['name' => 'confirmPassword', 'type' => 'string', 'required' => true, 'description' => 'Confirm new password', 'example' => 'newsecret123']], 'response' => '{"status": true, "message": "Password changed successfully"}'],
                ['method' => 'POST', 'endpoint' => '/api/auth/logout', 'description' => 'Logout.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "message": "Successfully logged out"}'],
            ],
            'Dashboard' => [
                ['method' => 'GET', 'endpoint' => '/api/dashboard', 'description' => 'Get main dashboard statistics.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": {...}}'],
            ],
            'Contacts' => [
                ['method' => 'GET', 'endpoint' => '/api/contacts', 'description' => 'List contacts (apiResource index).', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": [...]}'],
                ['method' => 'POST', 'endpoint' => '/api/contacts', 'description' => 'Create contact.', 'requires_auth' => true, 'parameters' => [['name' => 'name', 'type' => 'string', 'required' => true, 'description' => 'Name', 'example' => 'Alice'],['name' => 'phone', 'type' => 'string', 'required' => true, 'description' => 'Phone number', 'example' => '+11234567890']], 'response' => '{"status": true, "message": "Created"}'],
                ['method' => 'GET', 'endpoint' => '/api/contacts/{id}', 'description' => 'Get specific contact (apiResource show).', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": {...}}'],
                ['method' => 'PUT', 'endpoint' => '/api/contacts/{id}', 'description' => 'Update contact (apiResource update).', 'requires_auth' => true, 'parameters' => [['name' => 'name', 'type' => 'string', 'required' => false, 'description' => 'Name', 'example' => 'Alice Updated'],['name' => 'phone', 'type' => 'string', 'required' => false, 'description' => 'Phone', 'example' => '+11234567891']], 'response' => '{"status": true, "message": "Updated"}'],
                ['method' => 'DELETE', 'endpoint' => '/api/contacts/{id}', 'description' => 'Delete contact (apiResource destroy).', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "message": "Deleted"}'],
                ['method' => 'POST', 'endpoint' => '/api/contacts/import', 'description' => 'Import contacts via CSV.', 'requires_auth' => true, 'parameters' => [['name' => 'file', 'type' => 'file', 'required' => true, 'description' => 'CSV/Excel file', 'example' => 'contacts.csv']], 'response' => '{"status": true, "message": "Imported"}'],
                ['method' => 'GET', 'endpoint' => '/api/contacts/limits', 'description' => 'Get contact limits.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": {"limit": 1000, "used": 150}}'],
                ['method' => 'POST', 'endpoint' => '/api/contacts/delete', 'description' => 'Bulk remove contacts.', 'requires_auth' => true, 'parameters' => [['name' => 'contact_ids', 'type' => 'array', 'required' => true, 'description' => 'Contact IDs array', 'example' => '[1, 2, 3]']], 'response' => '{"status": true, "message": "Removed"}'],
            ],
            'Groups' => [
                ['method' => 'GET', 'endpoint' => '/api/groups', 'description' => 'Get all groups.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": [...]}'],
                ['method' => 'POST', 'endpoint' => '/api/groups', 'description' => 'Create a group.', 'requires_auth' => true, 'parameters' => [['name' => 'name', 'type' => 'string', 'required' => true, 'description' => 'Group name', 'example' => 'VIP Customers']], 'response' => '{"status": true, "message": "Created"}'],
                ['method' => 'GET', 'endpoint' => '/api/groups/{id}', 'description' => 'Get group details.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": {...}}'],
                ['method' => 'PUT', 'endpoint' => '/api/groups/{id}', 'description' => 'Update a group.', 'requires_auth' => true, 'parameters' => [['name' => 'name', 'type' => 'string', 'required' => true, 'description' => 'New group name', 'example' => 'Super VIP Customers']], 'response' => '{"status": true, "message": "Updated"}'],
                ['method' => 'DELETE', 'endpoint' => '/api/groups/{id}', 'description' => 'Delete a group.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "message": "Deleted"}'],
                ['method' => 'POST', 'endpoint' => '/api/groups/assign', 'description' => 'Add contacts to group.', 'requires_auth' => true, 'parameters' => [['name' => 'group_id', 'type' => 'integer', 'required' => true, 'description' => 'Group ID', 'example' => '1'],['name' => 'contact_ids', 'type' => 'array', 'required' => true, 'description' => 'Contact IDs', 'example' => '[4, 5, 6]']], 'response' => '{"status": true, "message": "Assigned"}'],
                ['method' => 'POST', 'endpoint' => '/api/groups/remove', 'description' => 'Remove contacts from group.', 'requires_auth' => true, 'parameters' => [['name' => 'group_id', 'type' => 'integer', 'required' => true, 'description' => 'Group ID', 'example' => '1'],['name' => 'contact_ids', 'type' => 'array', 'required' => true, 'description' => 'Contact IDs', 'example' => '[4, 5, 6]']], 'response' => '{"status": true, "message": "Removed"}'],
            ],
            'Templates' => [
                ['method' => 'GET', 'endpoint' => '/api/templates/sync-templates', 'description' => 'Sync approved WhatsApp templates.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "message": "Synced"}'],
                ['method' => 'GET', 'endpoint' => '/api/templates/user', 'description' => 'Get user templates.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": [...]}'],
                ['method' => 'GET', 'endpoint' => '/api/templates/user/{templateId}', 'description' => 'Get user template by ID.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": {...}}'],
                ['method' => 'GET', 'endpoint' => '/api/templates/filtered', 'description' => 'Get filtered templates.', 'requires_auth' => true, 'parameters' => [['name' => 'category', 'type' => 'string', 'required' => false, 'description' => 'Filter by category', 'example' => 'MARKETING']], 'response' => '{"status": true, "data": [...]}'],
                ['method' => 'GET', 'endpoint' => '/api/templates/status', 'description' => 'Get templates by status.', 'requires_auth' => true, 'parameters' => [['name' => 'status', 'type' => 'string', 'required' => false, 'description' => 'Filter by status', 'example' => 'APPROVED']], 'response' => '{"status": true, "data": [...]}'],
                ['method' => 'GET', 'endpoint' => '/api/templates/limits', 'description' => 'Get template limits.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": {"limit": 10}}'],
                ['method' => 'POST', 'endpoint' => '/api/templates/custom', 'description' => 'Add custom template.', 'requires_auth' => true, 'parameters' => [['name' => 'name', 'type' => 'string', 'required' => true, 'description' => 'Template name', 'example' => 'hello_world']], 'response' => '{"status": true, "message": "Created"}'],
                ['method' => 'PUT', 'endpoint' => '/api/templates/custom/{templateId}', 'description' => 'Edit custom template.', 'requires_auth' => true, 'parameters' => [['name' => 'name', 'type' => 'string', 'required' => true, 'description' => 'Template name', 'example' => 'hello_world_v2']], 'response' => '{"status": true, "message": "Updated"}'],
                ['method' => 'DELETE', 'endpoint' => '/api/templates/custom/{templateId}', 'description' => 'Delete custom template.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "message": "Deleted"}'],
                ['method' => 'PUT', 'endpoint' => '/api/templates/status/{templateId}', 'description' => 'Update template status.', 'requires_auth' => true, 'parameters' => [['name' => 'status', 'type' => 'string', 'required' => true, 'description' => 'New status', 'example' => 'REJECTED']], 'response' => '{"status": true, "message": "Updated"}'],
                ['method' => 'POST', 'endpoint' => '/api/template/create', 'description' => 'Create WhatsApp template in Meta.', 'requires_auth' => true, 'parameters' => [['name' => 'name', 'type' => 'string', 'required' => true, 'description' => 'Template name', 'example' => 'promo_alert'],['name' => 'category', 'type' => 'string', 'required' => true, 'description' => 'Category', 'example' => 'MARKETING'],['name' => 'language', 'type' => 'string', 'required' => true, 'description' => 'Language code', 'example' => 'en_US'],['name' => 'components', 'type' => 'array', 'required' => true, 'description' => 'WhatsApp template structure', 'example' => '[{"type":"BODY","text":"Hello {{1}}"}]']], 'response' => '{"status": true, "message": "Submitted"}'],
            ],
            'Bulk Messages' => [
                ['method' => 'GET', 'endpoint' => '/api/bulkmessage', 'description' => 'List campaigns (apiResource index).', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": [...]}'],
                ['method' => 'POST', 'endpoint' => '/api/bulkmessage', 'description' => 'Create campaign.', 'requires_auth' => true, 'parameters' => [['name' => 'campaignName', 'type' => 'string', 'required' => true, 'description' => 'Name', 'example' => 'Summer Sale'],['name' => 'templateId', 'type' => 'integer', 'required' => true, 'description' => 'Template ID', 'example' => '5'],['name' => 'groupIds', 'type' => 'array', 'required' => true, 'description' => 'Groups to send to', 'example' => '[1, 2]']], 'response' => '{"status": true, "message": "Processing"}'],
                ['method' => 'GET', 'endpoint' => '/api/bulkmessage/{id}', 'description' => 'Show campaign (apiResource).', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": {...}}'],
                ['method' => 'DELETE', 'endpoint' => '/api/bulkmessage/{id}', 'description' => 'Delete campaign (apiResource).', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "message": "Deleted"}'],
                ['method' => 'POST', 'endpoint' => '/api/bulk-messages/{id}/update', 'description' => 'Update campaign.', 'requires_auth' => true, 'parameters' => [['name' => 'campaignName', 'type' => 'string', 'required' => true, 'description' => 'Name', 'example' => 'Winter Sale']], 'response' => '{"status": true, "message": "Updated"}'],
                ['method' => 'GET', 'endpoint' => '/api/bulk-messages/{id}/stats', 'description' => 'Get campaign stats.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": {"sent": 100, "failed": 2}}'],
                ['method' => 'GET', 'endpoint' => '/api/bulk-messages/{id}/delivery-status', 'description' => 'Get delivery status.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": [...]}'],
                ['method' => 'GET', 'endpoint' => '/api/bulk-messages/{id}/delivery-status/summary', 'description' => 'Get summary delivery status.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": {...}}'],
                ['method' => 'GET', 'endpoint' => '/api/bulk-messages/{campaignId}/contact/{contactId}/delivery-status', 'description' => 'Get delivery status for a specific contact.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": {...}}'],
                ['method' => 'GET', 'endpoint' => '/api/bulk-messages/{id}/status', 'description' => 'Get running status.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": {"status": "completed"}}'],
                ['method' => 'PUT', 'endpoint' => '/api/bulk-messages/{id}/update-status', 'description' => 'Manually update running status.', 'requires_auth' => true, 'parameters' => [['name' => 'status', 'type' => 'string', 'required' => true, 'description' => 'Status string (paused, cancelled)', 'example' => 'paused']], 'response' => '{"status": true, "message": "Status updated"}'],
                ['method' => 'POST', 'endpoint' => '/api/bulk-messages/resend/{id}', 'description' => 'Resend failed and pending.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "message": "Resending initiated"}'],
                ['method' => 'GET', 'endpoint' => '/api/batch-settings', 'description' => 'Get batch settings.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": {...}}'],
                ['method' => 'POST', 'endpoint' => '/api/batch-settings', 'description' => 'Update batch settings.', 'requires_auth' => true, 'parameters' => [['name' => 'batchSize', 'type' => 'integer', 'required' => true, 'description' => 'Batch size', 'example' => '50'],['name' => 'batchDelay', 'type' => 'integer', 'required' => true, 'description' => 'Delay', 'example' => '5']], 'response' => '{"status": true, "message": "Settings updated"}'],
            ],
            'Packages' => [
                ['method' => 'POST', 'endpoint' => '/api/package/add', 'description' => 'Add package.', 'requires_auth' => true, 'parameters' => [['name' => 'packageName', 'type' => 'string', 'required' => true, 'description' => 'Name', 'example' => 'Pro Plan'],['name' => 'packageDesc', 'type' => 'string', 'required' => true, 'description' => 'Description', 'example' => 'For professionals'],['name' => 'price', 'type' => 'numeric', 'required' => true, 'description' => 'Price', 'example' => '49.99'],['name' => 'day', 'type' => 'integer', 'required' => true, 'description' => 'Days valid', 'example' => '30'],['name' => 'msgCount', 'type' => 'integer', 'required' => true, 'description' => 'Message Limit', 'example' => '10000'],['name' => 'contactCount', 'type' => 'integer', 'required' => true, 'description' => 'Contact Limit', 'example' => '5000']], 'response' => '{"status": true, "message": "Added"}'],
                ['method' => 'GET', 'endpoint' => '/api/package/get', 'description' => 'List packages.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": [...]}'],
                ['method' => 'GET', 'endpoint' => '/api/package/get/{id}', 'description' => 'Get package details.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": {...}}'],
                ['method' => 'PUT', 'endpoint' => '/api/package/edit/{id}', 'description' => 'Edit package.', 'requires_auth' => true, 'parameters' => [['name' => 'packageName', 'type' => 'string', 'required' => true, 'description' => 'Name', 'example' => 'Pro Plan V2']], 'response' => '{"status": true, "message": "Updated"}'],
                ['method' => 'DELETE', 'endpoint' => '/api/package/delete/{id}', 'description' => 'Delete package.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "message": "Deleted"}'],
            ],
            'Active Plans' => [
                ['method' => 'POST', 'endpoint' => '/api/plan/create', 'description' => 'Subscribe to plan.', 'requires_auth' => true, 'parameters' => [['name' => 'packageId', 'type' => 'integer', 'required' => true, 'description' => 'Package ID', 'example' => '2']], 'response' => '{"status": true, "message": "Subscribed"}'],
                ['method' => 'POST', 'endpoint' => '/api/plan/assign', 'description' => 'Assign package manually.', 'requires_auth' => true, 'parameters' => [['name' => 'userId', 'type' => 'integer', 'required' => true, 'description' => 'User ID', 'example' => '15'],['name' => 'packageId', 'type' => 'integer', 'required' => true, 'description' => 'Package ID', 'example' => '2']], 'response' => '{"status": true, "message": "Assigned"}'],
                ['method' => 'POST', 'endpoint' => '/api/plan/renew/{userId}', 'description' => 'Renew plan.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "message": "Renewed"}'],
                ['method' => 'GET', 'endpoint' => '/api/plan/user/{userId}', 'description' => 'Get user plan.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": {...}}'],
                ['method' => 'GET', 'endpoint' => '/api/plan/history/{userId}', 'description' => 'Get user plan history.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": [...]}'],
                ['method' => 'GET', 'endpoint' => '/api/plan/renewal-status', 'description' => 'Get renewal status.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": {...}}'],
            ],
            'Credits System' => [
                ['method' => 'POST', 'endpoint' => '/api/credits/create-order', 'description' => 'Create payment order.', 'requires_auth' => true, 'parameters' => [['name' => 'amount', 'type' => 'numeric', 'required' => true, 'description' => 'Amount', 'example' => '500']], 'response' => '{"status": true, "data": {"order_id": "ord_123"}}'],
                ['method' => 'POST', 'endpoint' => '/api/credits/verify', 'description' => 'Verify payment.', 'requires_auth' => true, 'parameters' => [['name' => 'payment_id', 'type' => 'string', 'required' => true, 'description' => 'Payment Gateway ID', 'example' => 'pay_abc123']], 'response' => '{"status": true, "message": "Verified"}'],
                ['method' => 'POST', 'endpoint' => '/api/credits/deduct', 'description' => 'Deduct credits manually.', 'requires_auth' => true, 'parameters' => [['name' => 'amount', 'type' => 'numeric', 'required' => true, 'description' => 'Amount to deduct', 'example' => '50']], 'response' => '{"status": true, "message": "Deducted"}'],
                ['method' => 'GET', 'endpoint' => '/api/credits/balance', 'description' => 'Get credit balance.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": {"balance": 1500}}'],
                ['method' => 'GET', 'endpoint' => '/api/credits/history', 'description' => 'Get transaction history.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": [...]}'],
                ['method' => 'GET', 'endpoint' => '/api/credits/report', 'description' => 'Get credit report.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": {...}}'],
            ],
            'Reports' => [
                ['method' => 'GET', 'endpoint' => '/api/reports', 'description' => 'Dashboard reports.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": {...}}'],
                ['method' => 'GET', 'endpoint' => '/api/campaigns', 'description' => 'Campaign reports.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": [...]}'],
                ['method' => 'GET', 'endpoint' => '/api/reports/campaign/{id}/delivery-status', 'description' => 'Campaign delivery status report.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": {...}}'],
            ],
            'Settings' => [
                ['method' => 'POST', 'endpoint' => '/api/settings/connect-facebook', 'description' => 'Connect Facebook.', 'requires_auth' => true, 'parameters' => [['name' => 'accessToken', 'type' => 'string', 'required' => true, 'description' => 'Facebook Access Token', 'example' => 'EAAbcdefg123...'],['name' => 'wabaId', 'type' => 'string', 'required' => true, 'description' => 'WABA ID', 'example' => '10987654321'],['name' => 'phoneNumberId', 'type' => 'string', 'required' => true, 'description' => 'Phone Number ID', 'example' => '1122334455']], 'response' => '{"status": true, "message": "Connected"}'],
                ['method' => 'POST', 'endpoint' => '/api/settings/refresh-token', 'description' => 'Refresh FB token.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "message": "Refreshed"}'],
                ['method' => 'POST', 'endpoint' => '/api/settings/save-config', 'description' => 'Save generic setting.', 'requires_auth' => true, 'parameters' => [['name' => 'key', 'type' => 'string', 'required' => true, 'description' => 'Setting Key', 'example' => 'timezone'],['name' => 'value', 'type' => 'string', 'required' => true, 'description' => 'Setting Value', 'example' => 'UTC']], 'response' => '{"status": true, "message": "Saved"}'],
                ['method' => 'GET', 'endpoint' => '/api/settings', 'description' => 'Get settings.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": {...}}'],
            ],
            'Notifications' => [
                ['method' => 'GET', 'endpoint' => '/api/notification', 'description' => 'List notifications.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": [...]}'],
                ['method' => 'POST', 'endpoint' => '/api/notification/mark-read', 'description' => 'Mark notification as read.', 'requires_auth' => true, 'parameters' => [['name' => 'notification_id', 'type' => 'integer', 'required' => true, 'description' => 'Notification ID', 'example' => '12']], 'response' => '{"status": true, "message": "Marked read"}'],
                ['method' => 'POST', 'endpoint' => '/api/notification', 'description' => 'Create notification.', 'requires_auth' => true, 'parameters' => [['name' => 'title', 'type' => 'string', 'required' => true, 'description' => 'Title', 'example' => 'System Alert'],['name' => 'message', 'type' => 'string', 'required' => true, 'description' => 'Message', 'example' => 'Server will restart in 5 mins.']], 'response' => '{"status": true, "message": "Created"}'],
                ['method' => 'GET', 'endpoint' => '/api/notification/{id}', 'description' => 'Get notification.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": {...}}'],
                ['method' => 'PUT', 'endpoint' => '/api/notification/{id}', 'description' => 'Update notification.', 'requires_auth' => true, 'parameters' => [['name' => 'title', 'type' => 'string', 'required' => true, 'description' => 'Title', 'example' => 'System Alert Updated']], 'response' => '{"status": true, "message": "Updated"}'],
                ['method' => 'DELETE', 'endpoint' => '/api/notification/{id}', 'description' => 'Delete notification.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "message": "Deleted"}'],
                ['method' => 'POST', 'endpoint' => '/api/notification/mark-all-read', 'description' => 'Mark all as read.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "message": "All marked read"}'],
            ],
            'Users (Admin)' => [
                ['method' => 'GET', 'endpoint' => '/api/users', 'description' => 'List users.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": [...]}'],
                ['method' => 'POST', 'endpoint' => '/api/users/add', 'description' => 'Add user.', 'requires_auth' => true, 'parameters' => [['name' => 'name', 'type' => 'string', 'required' => true, 'description' => 'Name', 'example' => 'Jane Smith'],['name' => 'email', 'type' => 'string', 'required' => true, 'description' => 'Email', 'example' => 'jane@example.com'],['name' => 'password', 'type' => 'string', 'required' => true, 'description' => 'Password', 'example' => 'secret123']], 'response' => '{"status": true, "message": "Added"}'],
                ['method' => 'GET', 'endpoint' => '/api/users/{id}', 'description' => 'Get user.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": {...}}'],
                ['method' => 'PUT', 'endpoint' => '/api/users/edit/{id}', 'description' => 'Edit user.', 'requires_auth' => true, 'parameters' => [['name' => 'name', 'type' => 'string', 'required' => true, 'description' => 'Name', 'example' => 'Jane Smith Updated']], 'response' => '{"status": true, "message": "Updated"}'],
                ['method' => 'DELETE', 'endpoint' => '/api/users/delete/{id}', 'description' => 'Delete user.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "message": "Deleted"}'],
                ['method' => 'PUT', 'endpoint' => '/api/users/status/{id}', 'description' => 'Update user status.', 'requires_auth' => true, 'parameters' => [['name' => 'status', 'type' => 'string', 'required' => true, 'description' => 'Status (active/inactive)', 'example' => 'inactive']], 'response' => '{"status": true, "message": "Status updated"}'],
            ],
            'Media' => [
                ['method' => 'GET', 'endpoint' => '/api/media', 'description' => 'List media.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": [...]}'],
                ['method' => 'POST', 'endpoint' => '/api/media', 'description' => 'Upload media.', 'requires_auth' => true, 'parameters' => [['name' => 'file', 'type' => 'file', 'required' => true, 'description' => 'Media file', 'example' => 'document.pdf']], 'response' => '{"status": true, "message": "Uploaded"}'],
                ['method' => 'GET', 'endpoint' => '/api/media/{id}', 'description' => 'Get media.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": {...}}'],
                ['method' => 'PUT', 'endpoint' => '/api/media/{id}', 'description' => 'Update media.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "message": "Updated"}'],
                ['method' => 'DELETE', 'endpoint' => '/api/media/{id}', 'description' => 'Delete media.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "message": "Deleted"}'],
                ['method' => 'GET', 'endpoint' => '/api/media/stats', 'description' => 'Media stats.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": {...}}'],
            ],
            'Conversations & Live Messages' => [
                ['method' => 'GET', 'endpoint' => '/api/conversations', 'description' => 'List conversations.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": [...]}'],
                ['method' => 'GET', 'endpoint' => '/api/conversations/{id}', 'description' => 'Show conversation.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": {...}}'],
                ['method' => 'GET', 'endpoint' => '/api/conversations/{conversationId}/media/{mediaId}', 'description' => 'Download chat media.', 'requires_auth' => true, 'parameters' => [], 'response' => 'Returns media file'],
                ['method' => 'GET', 'endpoint' => '/api/conversations/latest/contacts', 'description' => 'Latest contacts.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": [...]}'],
                ['method' => 'GET', 'endpoint' => '/api/conversations/unread', 'description' => 'Unread conversations.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": [...]}'],
                ['method' => 'PUT', 'endpoint' => '/api/conversations/{id}/status', 'description' => 'Update conversation status.', 'requires_auth' => true, 'parameters' => [['name' => 'status', 'type' => 'string', 'required' => true, 'description' => 'Status (open/closed)', 'example' => 'closed']], 'response' => '{"status": true, "message": "Updated"}'],
                ['method' => 'GET', 'endpoint' => '/api/conversations/stats', 'description' => 'Conversation stats.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": {...}}'],
                
                ['method' => 'POST', 'endpoint' => '/api/messages/send', 'description' => 'Send live message.', 'requires_auth' => true, 'parameters' => [['name' => 'conversationId', 'type' => 'integer', 'required' => true, 'description' => 'Conversation ID', 'example' => '1'],['name' => 'message', 'type' => 'string', 'required' => true, 'description' => 'Message text', 'example' => 'Hello! How can I help you?']], 'response' => '{"status": true, "message": "Sent"}'],
                ['method' => 'GET', 'endpoint' => '/api/messages/conversation/{conversationId}', 'description' => 'Get chat messages.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": [...]}'],
                ['method' => 'POST', 'endpoint' => '/api/messages/{conversationId}/mark-read', 'description' => 'Mark chat as read.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "message": "Marked read"}'],
                ['method' => 'GET', 'endpoint' => '/api/messages/eligible-conversations', 'description' => 'Get 24hr eligible conversations.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": [...]}'],
                ['method' => 'GET', 'endpoint' => '/api/messages/{conversationId}/check-eligibility', 'description' => 'Check 24hr eligibility.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": {"eligible": true}}'],
            ],
            'Test Routes' => [
                ['method' => 'GET', 'endpoint' => '/api/test/media-url', 'description' => 'Test route for media URL.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": {...}}'],
                ['method' => 'GET', 'endpoint' => '/api/test/global-plan', 'description' => 'Test route for global plan.', 'requires_auth' => true, 'parameters' => [], 'response' => '{"status": true, "data": {...}}'],
            ]
        ];

        return view('api-docs', compact('apis'));
    }
}
